name: Selenide tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    
    - name: Run tests with Maven
      run: mvn test
      
    - name: Collect build data
      if: always()
      run: expr $(date +%s) - $(START_TIME)
