name: Selenide tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install Google Chrome 
      run: |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml
